-- AlterTable
ALTER TABLE "Person" ADD COLUMN "mafia" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "laMafia" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "losAngeles" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "vegasMafia" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "networkMedia" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "personal" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "laActor" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "businessContact" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "magic" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Person" ADD COLUMN "modifiedByRickLax" BOOLEAN NOT NULL DEFAULT false;
